name: Validate and merge CSVs

on:
  push:
  pull_request:

jobs:
  validate:
    name: Validate and merge CSVs
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install dependencies
        working-directory: ./scripts
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run merge script
        working-directory: ./scripts
        run: |
          python merge_csvs.py

      - name: Diff new and old merged CSVs
        run: |
          git diff ./merged_cells_*.csv

      - name: Commit merged CSV
        uses: stefanzweifel/git-auto-commit-action@v4
        # Only run on pushes to main
        if: ${{ github.ref == 'refs/heads/main' && github.event_name == 'push' }}
        with:
          commit_message: "ci: commit merged cells CSV"
          commit_options: "--no-verify --signoff"
          file_pattern: "./merged_cells_*.csv"
